//vga
set_property PACKAGE_PIN E3 [get_ports clk ]
set_property PACKAGE_PIN M18 [get_ports reset ]
set_property PACKAGE_PIN A3 [get_ports {red1[0]} ]
set_property PACKAGE_PIN B4 [get_ports {red1[1]} ]
set_property PACKAGE_PIN C5 [get_ports {red1[2]} ]
set_property PACKAGE_PIN A4 [get_ports {red1[3]} ]
set_property PACKAGE_PIN C6 [get_ports {green1[0]} ]
set_property PACKAGE_PIN A5 [get_ports {green1[1]} ]
set_property PACKAGE_PIN B6 [get_ports {green1[2]} ]
set_property PACKAGE_PIN A6 [get_ports {green1[3]} ]
set_property PACKAGE_PIN B7 [get_ports {blue1[0]} ]
set_property PACKAGE_PIN C7 [get_ports {blue1[1]} ]
set_property PACKAGE_PIN D7 [get_ports {blue1[2]} ]
set_property PACKAGE_PIN D8 [get_ports {blue1[3]} ]
set_property PACKAGE_PIN B11 [get_ports hsync ]
set_property PACKAGE_PIN B12 [get_ports vsync ]
set_property IOSTANDARD LVCMOS18 [get_ports clk ]
set_property IOSTANDARD LVCMOS18 [get_ports reset ]
set_property IOSTANDARD LVCMOS18 [get_ports {red1[0]} ]
set_property IOSTANDARD LVCMOS18 [get_ports {red1[1]} ]
set_property IOSTANDARD LVCMOS18 [get_ports {red1[2]} ]
set_property IOSTANDARD LVCMOS18 [get_ports {red1[3]} ]
set_property IOSTANDARD LVCMOS18 [get_ports {green1[0]} ]
set_property IOSTANDARD LVCMOS18 [get_ports {green1[1]} ]
set_property IOSTANDARD LVCMOS18 [get_ports {green1[2]} ]
set_property IOSTANDARD LVCMOS18 [get_ports {green1[3]} ]
set_property IOSTANDARD LVCMOS18 [get_ports {blue1[0]} ]
set_property IOSTANDARD LVCMOS18 [get_ports {blue1[1]} ]
set_property IOSTANDARD LVCMOS18 [get_ports {blue1[2]} ]
set_property IOSTANDARD LVCMOS18 [get_ports {blue1[3]} ]
set_property IOSTANDARD LVCMOS18 [get_ports hsync ]
set_property IOSTANDARD LVCMOS18 [get_ports vsync ]

//tube
set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports rst_n]
//set_property IOSTANDARD LVCMOS18 [get_ports cnt_control]
set_property IOSTANDARD LVCMOS18 [get_ports {select_wei[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {select_wei[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {select_wei[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {select_wei[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {select_wei[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {select_wei[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {select_wei[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {select_wei[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data[0]}]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN M18 [get_ports rst_n]
//set_property PACKAGE_PIN J15 [get_ports cnt_control]
set_property PACKAGE_PIN J17 [get_ports {select_wei[0]}]
set_property PACKAGE_PIN J18 [get_ports {select_wei[1]}]
set_property PACKAGE_PIN T9 [get_ports {select_wei[2]}]
set_property PACKAGE_PIN J14 [get_ports {select_wei[3]}]
set_property PACKAGE_PIN P14 [get_ports {select_wei[4]}]
set_property PACKAGE_PIN T14 [get_ports {select_wei[5]}]
set_property PACKAGE_PIN K2 [get_ports {select_wei[6]}]
set_property PACKAGE_PIN U13 [get_ports {select_wei[7]}]
set_property PACKAGE_PIN T10 [get_ports {data[0]}]
set_property PACKAGE_PIN R10 [get_ports {data[1]}]
set_property PACKAGE_PIN K16 [get_ports {data[2]}]
set_property PACKAGE_PIN K13 [get_ports {data[3]}]
set_property PACKAGE_PIN P15 [get_ports {data[4]}]
set_property PACKAGE_PIN T11 [get_ports {data[5]}]
set_property PACKAGE_PIN L18 [get_ports {data[6]}]
set_property PACKAGE_PIN H15 [get_ports {data[7]}]


//bluetooth
set_property IOSTANDARD LVCMOS33 [get_ports data_rx]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rx_int]
set_property IOSTANDARD LVCMOS33 [get_ports flag]
set_property IOSTANDARD LVCMOS33 [get_ports {data_tx[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_tx[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_tx[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_tx[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_tx[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_tx[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_tx[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_tx[7]}]
set_property PACKAGE_PIN G1 [get_ports data_rx]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN M18 [get_ports rst_n]
set_property PACKAGE_PIN N14 [get_ports rx_int]
set_property PACKAGE_PIN H17 [get_ports flag]
set_property PACKAGE_PIN R18 [get_ports {data_tx[0]}]
set_property PACKAGE_PIN V17 [get_ports {data_tx[1]}]
set_property PACKAGE_PIN U17 [get_ports {data_tx[2]}]
set_property PACKAGE_PIN U16 [get_ports {data_tx[3]}]
set_property PACKAGE_PIN V16 [get_ports {data_tx[4]}]
set_property PACKAGE_PIN T15 [get_ports {data_tx[5]}]
set_property PACKAGE_PIN U14 [get_ports {data_tx[6]}]
set_property PACKAGE_PIN T16 [get_ports {data_tx[7]}]

